name: Generate sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Generate XML Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://atividadesescolares.net/
          path-to-root: .
          exclude-paths: 404.html
          # Esta linha abaixo remove os PDFs do sitemap
          include-pdf: false

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          
          # 1. Adiciona o sitemap.xml modificado
          git add sitemap.xml
          
          # 2. Faz o commit local
          git commit -m "Automated sitemap update (remover PDFs)" || echo "Sem mudan√ßas"
          
          # 3. Sincroniza com o servidor
          git pull --rebase origin main
          
          # 4. Envia para o GitHub
          git push origin main
