name: Generate sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Importante para evitar erros de histórico

      - name: Generate XML Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://atividadesescolares.net/
          path-to-root: .
          exclude-paths: 404.html

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          # O segredo está nestas linhas abaixo:
          git pull --rebase origin main
          git commit -m "Automated sitemap update" || exit 0
          git push
