name: Generate sitemap

on:
  push:
    branches: [ main ]  # Toda vez que você salvar um arquivo na main, ele atualiza o sitemap

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate XML Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://atividadesescolares.net/
          path-to-root: .
          # Aqui ele ignora arquivos que não precisam estar no Google
          exclude-files: '404.html' 

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          git commit -m "Automated sitemap update" || exit 0
          git push
